work_dir: ./NTU60_Xsub/joint/free1

# feeder
feeder: feeder.feeder_ntu.Feeder
train_feeder_args:
  data_path: ./dataset/data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  free: True

val_feeder_args:
  data_path: ./dataset/data/ntu/NTU60_CS.npz
  split: val
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

test_feeder_args:
  data_path: ./dataset/data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 64 
test_batch_size: 64
num_epoch: 80
patience: 20
free_iter: 4
epsilon: 3.0

phase: free

num_worker: 0


